### ISSUE TITLE
Interface design in XAML (epic)

### ISSUE THREAD

**Issue by Jackenmen** [pginf-pg-9kisi2023/indexer-app#1]
- [x] Menu with the following submenus:
    - File (Plik)
        - New session (Utwórz nową sesję)
        - Load session (Wczytaj sesję)
        - Add file or folder... (Dodaj obraz lub folder)
        - Save session (Zapisz sesję)
        - Save session as... (Zapisz sesję jako...)
        - Export (Wyeksportuj)
        - Export as... (Wyeksportuj do...)
        - Close session (Zamknij sesję)
        - Exit (Zamknij)
    - Help (Pomoc)
        - Available key shortcuts (Dostępne skróty klawiaturowe)
        - About (O programie)
- [x] Status bar
    - Text aligned to the left which will eventually represent the path to the currently indexed image
    - Text aligned to the right which will eventually represent the coordinates pointed at with the mouse cursor on the image
- [x] Big (main) image
    - eventually, this will be a preview of the currently indexed image
- [x] Left (collapsible) sidebar containing:
    - [x] a list of loaded images with a visible scrollbar
    - [x] a list of selected points with a visible scrollbar
    - [x] a list of points that still need to be selected
        - currently, this is not shown on the interface "draft" which means that we need to figure how we want this to look like
- [x] Right sidebar containing:
    - [x] Text
        - eventually, this will represent the preliminary position of the currently labeled point
    - [x] Image
        - eventually, this will be a "magnifier" showing a part of the image in a close-up
    - [x] Slider with the default of 100% (minimum) allowing the user to change the zoom factor of the magnifier with 100 point steps up to the the maximum of 500%
    - [x] Image
        - eventually, this will be the reference image for the currently labeled point
    - [x] Text
        - eventually, this will be the description for the currently labeled point

Details about the behavior of the interface:
- [x] Interface should be responsive when the window size is changed
    - It may make sense to set a minimum window size
- [x] Elements in the sidebars should be centered within them

Interface draft:
![Image](https://user-images.githubusercontent.com/6032823/205357975-d1c0248a-7000-46c6-ac09-2f5a576f01cb.png)
